services:
  postgres:
    image: postgres:16-alpine
    container_name: tapaybusca-db
    environment:
      POSTGRES_USER: tapaybusca
      POSTGRES_PASSWORD: tapaybusca
      POSTGRES_DB: tapaybusca
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
